Realtime communication
alculquicondor/VRaze pull request #3
Opened 2017-11-18 00:55 UTC by andialuis

2017-11-18 00:58 UTC, andialuis commented
Getting sha1-key:

keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android

2017-11-18 01:33 UTC, alculquicondor requested changes

2017-11-18 01:33 UTC, alculquicondor commented on app/src/main/AndroidManifest.xml
> +        <!--action android:name="android.intent.action.MAIN" />
remove these lines

2017-11-18 01:33 UTC, alculquicondor commented on app/src/main/AndroidManifest.xml
> +        android:label="VRaze"
`@string/app_name`

2017-11-18 01:33 UTC, alculquicondor commented on app/src/main/cpp/vraze_jni.cc
> +(JNIEnv* env, jobject obj, jlong controller_paint_jptr,float x, float y, float dir0, float dir1){
`dir_x` and `dir_y`

2017-11-18 01:33 UTC, alculquicondor commented on app/src/main/java/pe/edu/ucsp/vraze/MainActivity.java
>      Log.d(TAG,"x: " + String.valueOf(x) + " y: " + String.valueOf(y));
We won't be needing these logs anymore. But we can remove them later.

2017-11-18 01:33 UTC, alculquicondor commented on app/src/main/java/pe/edu/ucsp/vraze/MainActivity.java
> +
you can already call the `nativeMoveCar`

2017-11-18 01:33 UTC, alculquicondor commented on app/src/main/java/pe/edu/ucsp/vraze/Menu.java
> +    mMsgBuf[0] = (byte) x;
https://stackoverflow.com/questions/14619653/converting-a-float-to-a-byte-array-and-vice-versa-in-java

2017-11-19 15:05 UTC, alculquicondor commented
Looks good. Let's wait for the fix for the Daydream activity. Then we can cleanup code and merge.

2017-11-24 13:51 UTC, merged